"""added limits len name field and add new fields description both model dictionary, topic model

Revision ID: f243fe71f02a
Revises: 362f7077de54
Create Date: 2025-03-22 13:01:25.343238

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f243fe71f02a"
down_revision: Union[str, None] = "362f7077de54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dictionary",
        sa.Column(
            "description",
            sa.String(length=150),
            nullable=True,
            comment="Описание",
        ),
    )
    op.add_column(
        "topic",
        sa.Column(
            "description",
            sa.String(length=150),
            nullable=True,
            comment="Описание",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("topic", "description")
    op.drop_column("dictionary", "description")
    # ### end Alembic commands ###
