"""add chat_ids to tg_users

Revision ID: 2ede4b0efbdf
Revises: 040b3ad755a8
Create Date: 2025-04-10 17:21:22.753551

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2ede4b0efbdf"
down_revision: Union[str, None] = "040b3ad755a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tg_users", sa.Column("chat_ids", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tg_users", "chat_ids")
    # ### end Alembic commands ###
