"""add tg_user_topic_progress table

Revision ID: ffc67a29f81e
Revises: 90a92862202d
Create Date: 2025-04-09 18:41:54.216627

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ffc67a29f81e"
down_revision: Union[str, None] = "90a92862202d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tg_user_topic_progress",
        sa.Column(
            "progress",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Прогресс 0-100",
        ),
        sa.Column("tg_user_id", sa.BigInteger(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tg_user_id"],
            ["tg_users.tg_id"],
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topic.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("topic", "progress")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "topic",
        sa.Column(
            "progress",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
            comment="Прогресс 0-100",
        ),
    )
    op.drop_table("tg_user_topic_progress")
    # ### end Alembic commands ###
