"""added progress in topic table

Revision ID: 8385c0677382
Revises: cac08a858355
Create Date: 2025-03-22 19:15:45.651970

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8385c0677382"
down_revision: Union[str, None] = "cac08a858355"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "topic",
        sa.Column(
            "progress",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Прогресс 0-100",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("topic", "progress")
    # ### end Alembic commands ###
