"""fix model

Revision ID: 362f7077de54
Revises: 4943afbb1a8d
Create Date: 2025-03-22 00:04:36.042793

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "362f7077de54"
down_revision: Union[str, None] = "4943afbb1a8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "words",
        "trys",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_comment="Попытки",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "words",
        "trys",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_comment="Попытки",
    )
    # ### end Alembic commands ###
