"""add unique constraint in tg_user_topic_progress table

Revision ID: ec09d6bd3864
Revises: ffc67a29f81e
Create Date: 2025-04-09 18:46:38.663197

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ec09d6bd3864"
down_revision: Union[str, None] = "ffc67a29f81e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "idx_unique_topic_id_tg_user_id",
        "tg_user_topic_progress",
        ["topic_id", "tg_user_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "idx_unique_topic_id_tg_user_id",
        "tg_user_topic_progress",
        type_="unique",
    )
    # ### end Alembic commands ###
