"""fix model

Revision ID: 4943afbb1a8d
Revises: 27cc4c88807f
Create Date: 2025-03-21 23:14:46.860301

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4943afbb1a8d"
down_revision: Union[str, None] = "27cc4c88807f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "topic",
        sa.Column(
            "type_translation",
            sa.String(),
            nullable=False,
            comment="Тип перевода",
        ),
    )
    op.drop_column("words", "type_translation")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "words",
        sa.Column(
            "type_translation",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Тип перевода",
        ),
    )
    op.drop_column("topic", "type_translation")
    # ### end Alembic commands ###
