"""add unique constraint

Revision ID: 90a92862202d
Revises: 501ba7c18181
Create Date: 2025-04-04 20:23:36.375367

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "90a92862202d"
down_revision: Union[str, None] = "501ba7c18181"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("tg_users_constraint", "tg_users", ["tg_id"])
    op.create_unique_constraint(
        "idx_unique_word_id_tg_user_id", "word_trys", ["word_id", "tg_user_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("idx_unique_word_id_tg_user_id", "word_trys", type_="unique")
    op.drop_constraint("tg_users_constraint", "tg_users", type_="unique")
    # ### end Alembic commands ###
