"""added limits len name field and add new fields description both model dictionary, topic model

Revision ID: cac08a858355
Revises: f243fe71f02a
Create Date: 2025-03-22 18:15:29.973188

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cac08a858355"
down_revision: Union[str, None] = "f243fe71f02a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "words",
        "trys",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_comment="Попытки",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "words",
        "trys",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_comment="Попытки",
    )
    # ### end Alembic commands ###
