"""change type chat_ids in tg_users

Revision ID: 9a59773fbb96
Revises: 2ede4b0efbdf
Create Date: 2025-04-10 20:05:52.819685

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9a59773fbb96"
down_revision: Union[str, None] = "2ede4b0efbdf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tg_users",
        sa.Column("chats", postgresql.ARRAY(sa.String()), nullable=True),
    )
    op.drop_column("tg_users", "chat_ids")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tg_users",
        sa.Column(
            "chat_ids",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("tg_users", "chats")
    # ### end Alembic commands ###
