"""set nullebel true dictionary in topic

Revision ID: 2831d7ac46da
Revises: 9a59773fbb96
Create Date: 2025-05-30 16:18:01.847987

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2831d7ac46da"
down_revision: Union[str, None] = "9a59773fbb96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "topic", "dictionary_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "topic", "dictionary_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
